### ISSUE TITLE
errors when install  and using quickstart

### ISSUE THREAD

**Issue by Sinanaltundag** [AgoraIO-Usecase/AgoraChat-UIKit-web#59]
I try npm and yarn for install this package in different projects but some errors occured

```
16 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.70.0 compiled with 87 errors in 1950 ms
```
sample error:
```
ERROR in ./node_modules/chat-callkit/es/modules/singleCall/index.js 355:15-42
export 'WebIM' (imported as 'WebIM') was not found in '../callManager' (possible exports: callManager, client)
```
```
Could not find a declaration file for module 'agora-chat-uikit'. 'c:/path/my/project/node_modules/agora-chat-uikit/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/agora-chat-uikit` if it exists or add a new declaration (.d.ts) file containing `declare module 'agora-chat-uikit';`ts(7016)
```
I try "npm i --save-dev @types/agora-chat-uikit" but get new errors and not installed

**Comment by myZhangDong** [comment]
ERROR in ./node_modules/chat-callkit/es/modules/singleCall/index.js 355:15-42
export 'WebIM' (imported as 'WebIM') was not found in '../callManager' (possible exports: callManager, client)

it seems to be caused by no installation dependency,  You need to install 'agora-chat', 'redux', 'react-redux', 'react-dom', 'react'.

'agora-chat-uikit' does not support typescript yet.

**Comment by myZhangDong** [comment]
Please use version 1.2.0
